k8snetworkplumbingwg/sriov-network-device-plugin

- deployments/crdnetwork.yaml
- deployments/pod-tc1.yaml
- deployments/pod-tc2.yaml
- deployments/pod-tc3.yaml
- deployments/sriov-crd.yaml
This commits update the following templates to work with
multus v3.0 changes:
* deployments/crdnetwork.yaml
* deployments/sriov-crd.yaml
* deployments/pod-tc(1/2/3).yaml
> Update templates to use NetworkAttachmentDefinition

- cmd/sriovdp/sriov-device-plugin.go
Some inodes there, e.g. bonding_masters, may not be directories at all but
regular files. Without the fix, the plugin just panics with segfault when such
scenario occurs.
> Gracefully handle non-dirs under /sys/class/net/

- Dockerfile
This commit allows 'make build' to build device plugin binary from local dependency instead of having to update packages before building. Also it keeps original 'make' behavior to run a "fmt", "lint" and "build".
This change is helpful when building device plugin binary from a local environment without internet access.
> use 'make build' instead of 'make' in Dockerfile 

- Dockerfile
- Makefile
This changes will allow proxy settings to be passed in for docker
as well as Env variable in Dockerfile.
simply invoke 'make image HTTP_PROXY=http://whateverhost:port'.
Change-Id: I4264b2a96d86a6feedee1b21a9f1bac8e74c8fc5
> allowing proxy-settings to be passed in for Docker

- images/sriovdp-daemonset.yaml
the /dev voume is not needed and cause some unexpected issues.
Also removed the hostNetwork flag as well.
Change-Id: If5447a768ebb0361e2d36b3d9effc5b95965cdd8
> removed /dev volume from daemonset spec

- cmd/sriovdp/sriov-device-plugin.go
Watch existence of plugin endpoint every five minutes. 
When Kubelet gets restarted:
- Terminate ListAndWatch call
- Re-discover root devices
- Re-register device plugin to Kubelet
> detect Kubelet restarts and auto re-register

- cmd/sriovdp/sriov-device-plugin.go
Previously sm.Probe() is evaluated first in the
ListAndWatch for loop so there is no problem by
adding continue in the select case of 10 seconds;
but with recent change, sm.Probe() is moved under
select which causes an endless 10 seconds waiting
and Probe() is never invoked until the termSignal
is received. Fix it by removing continue.
> fix endless waiting

- README.md
- pkg/resources/genericPool.go
- pkg/resources/netDevicePool.go
- pkg/resources/pool_stub.go
- pkg/resources/server.go
- pkg/resources/uioPool.go
- pkg/resources/vfioPool.go
- pkg/types/types.go
This PR is based on [discussion](https://github.com/intel/sriov-network-device-plugin/pull/26#discussion_r229915970) on Env variable naming scheme.
Env variable with device IDs will be exported in following format: `PCIDEVICE_INTEL_COM_NET_A=0000:87:10.0;0000:87:11.6`
> Env variable name with proposed scheme

- images/sriovdp-daemonset.yaml
The directory is not generally accessible to unprivileged pods.
Instead, log to stderr and allow admins to decide how they want to
manage service logs in their cluster.
> Don't log to /var/log/ by default

- images/sriovdp-daemonset.yaml
With policy = Never, the image won't be pulled by kubelet, meaning the
deployment will fail to start pods due to missing image in registry.
> Pull the latest image for daemon set

- Dockerfile
- images/entrypoint.sh
Switching base image to alpine which is lightweight and we can get golang environment.  This change also reduces the docker build time and the final image size(17.4MB instead of 521MB)
> build docker image from alpine base image

- images/entrypoint.sh
Now that we switched to alpine that doesn't have bash installed, the
script fails to execute.
There were a bunch of bashisms in the script (detected by
checkbashisms tool), specifically:
1. built-in posix shell echo doesn't support -e. To overcome this, we
execute /bin/echo that is busybox version of echo guaranteed to support
it.
2. `function` keyword is not part of posix shell syntax. Just remove it.
With that, we should be able to safely switch shebang to /bin/sh.
> Don't use bash to run /entrypoint.sh

- cmd/sriovdp/sriov-device-plugin.go
When SR-IOV device plugin runs on node without SR-IOV configured devices, it'll still advertise the resourceName of devices but with zero capacity and allocatable device.
Fixes #62
> ignore error when no SR-IOV capable PF is found

- deployments/pod-sriovdp.yaml
Add mount for /etc/pcidp/config.json the default configuration
file, which was casuing pod status to be "RunContainerError" when
running the plugin as pod
Fixes #73
> Modify template pod-sriovdp.yaml to mount default config file

- cmd/sriovdp/sriov-device-plugin.go
- deployments/pod-tc1.yaml
- deployments/pod-tc2.yaml
- deployments/pod-tc3.yaml
- deployments/sriov-crd.yaml
- add command line parameter ``nic-model``
-- ``nic-model`` parameter can be added multiple times to enable different NIC models
-- ``nic-model`` parameter is in the format of ``<vendorID>-<deviceID>``, e.g. ``0x8086-0x10fb``
- change default ``resourceName`` to ``netdev/sriov``
> allow specifying NIC models to be discovered

- Makefile
This PR adds support to build statically linked binary.
Usage: make STATIC=y
Implements #87.
> Added support to build statically linked binary

- Makefile
This fix will enable make to invoke build on source file modification.
Change-Id: I4c29bb115e40239db0c3675c3066c1f050e3258d
> fix make to build on source file update

- Makefile
Normally when building the binary and running ``make``, it's expected to build from local vendor dependencies instead of having to retrieve dependency update remotely. With this change, it allows user to build locally without having a internet connection. For glide update, we could still use ``make vendor``.
> remove vendor dependency for bulid/test/lint rules in Makefile

- README.md
- cmd/sriovdp/sriov-device-plugin.go
- cmd/sriovdp/sriovdp_test.go
- deployments/pod-sriovdp.yaml
- glide.lock
- images/README.md
- images/sriovdp-daemonset.yaml
KubeletPluginWatcher is enabled by default in kube-1.12.0;
This commit switches registration of Device Plugin to watcher
mode instead of explicitly calling Register in Device Plugin.
This also means Device Plugin will only work with
KubeletPluginWatcher featureGate enabled.
> switch to kubelet device plugin watcher mode

- deployments/pod-sriovdp.yaml
- images/README.md
- images/sriovdp-daemonset.yaml
With kubelet plugin watcher mode enabled, either
{kubelet_root_dir}/device-plugins or
{kubelet_root_dir}/plugins_registry registration
pathes will be used depending on different kube
versions. This commit changes device socket mount
path to {kubelet_root_dir} in order to support both.
> fix device socket mount path

- .travis.yml
glide is not required when building binary or image,
all the vendor packages should already be updated
properly for a successful build; otherwise we need
to explicitly update the vendor dependencies with
'make vendor' and send a PR.
> travis: remove glide install

- Dockerfile
`ghw.PCI()` trys to download pci.ids.gz form Internet if it cannot be found locally. We should not assume the container always has Internet access available. 
Event when the container has Internet access, due to there is no ca certificates installed, the following error pops up.
"error discovering host network devicesdiscoverDevices(): error getting PCI info: Get https://pci-ids.ucw.cz/v2.2/pci.ids.gz: x509: certificate signed by unknown authority"
> Add pci.ids.gz file to image to avoid downloading it at runtime

- deployments/pod-sriovdp.yaml
- images/sriovdp-daemonset.yaml
Since the hwdata package is being installed in docker image to
avoid downloading the pci.ids at runtime, the host mount is no
longer needed.
> remove host mount for /usr/share/hwdata

- pkg/utils/utils.go
- pkg/utils/utils_test.go
The GetPFName() is used to determine a device's PF name if it was
an SR-IOV VF. For non SR-IOV devices, it would try to get device's
corresponding kernel net interface name. This name is unavailable
if the interface is not in the same namespace(see #141) or the
device is enabled for dpdk mode.
In those cases this function should return appropriate errors to
the caller if no interface name is found.
Change-Id: Id7c6662a2a86f20eb91fcfc4d4f965cd31f9d9b0
> fix a runtime error if PF interface name not found

- pkg/resources/factory.go
This patch fixes an issue where selecting igb_uio drivers did not
provide required device specs to container runtime.
Change-Id: I9c1e33bbb77bfc0a7e7af66fa351eafa5e067d90
> fix: igb_uio export device specs

- README.md
- pkg/resources/deviceSelectors.go
- pkg/resources/deviceSelectors_test.go
- pkg/resources/factory.go
- pkg/resources/factory_test.go
- pkg/resources/pciNetDevice.go
- pkg/resources/pciNetDevice_test.go
- pkg/resources/pool_stub_test.go
- pkg/resources/server_test.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
- pkg/utils/netlink_provider.go
Add the ability to filter according to a device's link type.
This will enable a user to filter SR-IOV resources according
to link type, allowing the creation of resource pools based on
the underlying fabric a device is connected to
(e.g ethernet, infiniband).
> Add Link Type selector

- cmd/sriovdp/manager.go
- cmd/sriovdp/manager_test.go
When PF is connected to a dhcp network, creation of VFs
will result in IP address being assigned to each VF. Current
Device Plugin ignore such devices and doesn't count it as
allocatable devices.
This commit changes such behavior by checking and filtering
out device with default route, leaving other devices as
available resource.
> only exclude default route interface

- README.md
After the merge of the README update I realized I forgot to update the table of contents.
Then when I started fixing it I realized others also forgot to do it :)
I rechecked all entries and everything should be now up-to-date, clickable, and properly indented!
> Fixing all entries in the README's table of contents

- pkg/resources/pciNetDevice.go
- pkg/resources/pciNetDevice_test.go
- pkg/utils/utils.go
There are situation where a VF's PF information is not accessble, for example
in VM pass-through mode. This change will allow device plugin to simply log
such events and allow such devices to be added in the discovered device list.
> allow device to be added without PF info

- README.md
Added references to the config map rather than the config.json in the deployment instructions where appropriate. Some minor updates to capitalization and spelling.
> Documentation updated to refer to config map. Minor documentation fixes

- README.md
The docker image build steps mistakenly had 'make' command instead
of 'make image'. Also, encouraged users to use pre-built images
from docker hub instead of building it locally.
> update README.md with missing image build command

- cmd/sriovdp/manager.go
- cmd/sriovdp/manager_test.go
- docs/README.md
- docs/ddp/README.md
- docs/ddp/configMap.yaml
- docs/ddp/crd-sriov-gtp.yaml
- docs/ddp/crd-sriov-pppoe.yaml
- docs/ddp/pod-gtp.yaml
- docs/ddp/pod-pppoe.yaml
- images/Dockerfile
- pkg/resources/ddpSelector.go
- pkg/resources/ddpSelector_test.go
- pkg/resources/factory.go
- pkg/resources/factory_test.go
- pkg/resources/pciNetDevice.go
- pkg/resources/server_test.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
- pkg/utils/ddp.go
- pkg/utils/ddp_test.go
Introducing new selector that can filter devices based on the DDP profile a SR-IOV NIC is running with.
For more information on DDP please see [here](https://software.intel.com/en-us/articles/dynamic-device-personalization-for-intel-ethernet-700-series).
> add ddp selector

- .travis.yml
travis-ci build build is failing after merging #86.
The deployment script contains both single and double quotes and
causing issues.
> fix travis-ci build error due to bash quotes issue

- .travis.yml
The deployment scripts weren't parsing properly and resulted in
errors.
This change also uses the REGISTRY_USER variable for image tagging
so that deployement can be tested on local forks with their own
REGISTRY_USER value.
Change-Id: Idf03b5c8c256f63ce01beff5c316cb8c5a786db3
> fix travis deployment script errors

- Makefile
Files downloaded by 'go mod' are not writable (removable).
Use the recommended way of cleaning modules [1]
[1] https://github.com/golang/go/issues/27161#issuecomment-415213240
Fixes #232 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
> Use "go clean" to clean modules

- pkg/resources/deviceSelectors.go
Current behaviour of pfName selector adds devices that do not have
PF names available. For instance, if there is a PF attached to
igb_uio driver and VFs are created under that PF, those VFs will
have no PF name information. If a resource config prvides the
"pfName" selector any VFs under that PF(igb_uio driver) will
wrongly be added to that pool. This happens because this selector
matches PF name with string.HasPrefix() method and providing ""
for PF name results in true.
Fix: skip devices that do not have PF names when "pfNames" selector
is used.
Change-Id: I1ddd49743ef2e8f25718285e80c16dfcef4c90f5
Signed-off-by: Abdul Halim <abdul.halim@intel.com>
> fix pfNames selector to skip device with no PF name

- docs/README.md
- docs/bond/bond-crd.yaml
BKC for bond cni will change as per: https://github.com/intel/bond-cni/pull/15
This doc change reflects that in the bonding guide hosted here.
Waiting for above pull request to be merged before this PR.
> added bond config changes reflecting failOverMac change in bond cni

- README.md
- cmd/sriovdp/manager_test.go
- pkg/factory/factory.go
- pkg/factory/factory_test.go
- pkg/netdevice/netDeviceProvider.go
- pkg/netdevice/netDeviceProvider_test.go
- pkg/resources/deviceSelectors.go
- pkg/resources/deviceSelectors_test.go
- pkg/types/types.go
This makes device plugin to support VM usecase in which
vf (or) virtio devices can be enumerated into a device
pool using its pci addresses.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
> Add pciAddresses selectors for VM usecase

- docs/vf-setup.md
Added updated version of VF creation guide from SR-IOV CNI docs to the device plugin docs folder as per https://github.com/intel/sriov-cni/issues/74
Input welcome to update the info on VF creation here. 
Once this is merged it can be linked from the new SR-IOV CNI docs contained in https://github.com/intel/sriov-cni/pull/127
> added VF set up guide to docs

- README.md
- pkg/netdevice/netResourcePool.go
- pkg/netdevice/vhostNet.go
- pkg/types/types.go
New option to share /dev/vhost-net, useful for dpdk app to implement an
exceptional path.
Let's enable to share this resource along other VF.
Link: https://doc.dpdk.org/guides/howto/virtio_user_as_exceptional_path.html
Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
> netdevice: add option to share /dev/vhost-net

- docs/README.md
- docs/config-file/README.md
- images/entrypoint.sh
config-file cmd option is supported in sriovdp binary but not in image entrypoint script.
With this commit, config-file option is added in the entrypoint.sh which can be used to
specify individual configuration for device plugin daemonSet pod for a certain node.
Compared with global device plugin configMap, it allows more granular control over
which resource shall be exposed on a specific node.
> add --config-file in entrypoint.sh

- images/entrypoint.sh
On Pod / DaemonSet termination, Kubernetes sends SIGTERM to the first
process (pid 1).
In order to ensure the SR-IOV Device Plugin daemon receives the signal
and it can gracefully clean up, use "exec" in the entrypoint script.
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
> entrypoint: use exec to run Device Plugin

- README.md
- docs/dpdk/README-virt.md
- docs/dpdk/configMap-virt.yaml
- docs/dpdk/pod_testpmd_virt.yaml
- pkg/resources/vfioResource.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This PR is required for https://github.com/openshift/sriov-network-operator/pull/369.
This PR enables the mapping of a no-iommu vfio device into a container.  
Associated system configuration enables no-iommu for the vfio-pci driver.
This PR is required to allow Kubernetes to run in a virtual environment that does not provide a virtualized iommu.  The initial target environment is OpenStack.  OpenStack Nova does not currently provide a virtualized iommu. Support for vfio-noiommu was added to linux a few years ago with the caveats outlined below...
`There is really no way to safely give a user full access to a DMA
capable device without an IOMMU to protect the host system.  There is
also no way to provide DMA translation, for use cases such as device
assignment to virtual machines. …
> Add support for running inside a VM with vfio-noiommu

- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
- docs/config-file/README.md
This commit removes the HostPID cap from deployment
examples as it is not needed for proper operation
of device plugin.
> Remove hostPID cap from deployment examples

- pkg/accelerator/accelDevice.go
- pkg/factory/factory.go
- pkg/factory/factory_test.go
- pkg/netdevice/netInfoProviders.go
- pkg/netdevice/netResourcePool.go
- pkg/netdevice/netResourcePool_test.go
- pkg/netdevice/pciNetDevice.go
- pkg/netdevice/pciNetDevice_test.go
- pkg/resources/genericInfoProvider.go
- pkg/resources/genericInfoProvider_test.go
- pkg/resources/pciDevice.go
- pkg/resources/uioInfoProvider.go
- pkg/resources/uioInfoProvider_test.go
- pkg/resources/vfioInfoProvider.go
- pkg/resources/vfioInfoProvider_test.go
- pkg/types/mocks/DeviceInfoProvider.go
- pkg/types/mocks/ResourceFactory.go
- pkg/types/types.go
Currently, the generation of DeviceSpecs is done in two different places.
First, the PciNetDevice is created, and it may create alternative deviceSpecs objects (e.g: `RdmaSpecs`) that are stored within `PciNetDevice`. Then the underlying PciDevice is created and, based on the driver that is bound to the device, an implementation of the  `DeviceInfoProvider` interface is created, which provides more DeviceSpecs.
After, when Allocate() is called,  the `NetResourcePool` has some logic to append these deviceSpecs.
This imposes a limitation on how flexibly we can choose what DeviceSpecs are exposed (must be determined by the driver) and fosters ad-hoc DeviceSpec-appending logic (see how vhostNet DeviceSpec was added).
In order to improve this, I'd like to propose the generalization of …
> Use DeviceInfoProviders for all DeviceSpec generation

- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
Before I can create a new release which would increment the tag ref, I would like to update the daemonset images versions. I understand this would be invalid until a new release would be created but I would rather this than creating a release which referenced old docker image version. 
Opinions?
> Increment docker image version to v3.3

- Makefile
- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
- docs/config-file/README.md
- images/README.md
docker.io may not be the default container repository
url in some runtime configurations.
Signed-off-by: Zenghui Shi <zshi@redhat.com>
> Specify image url repo explicitly

- images/Dockerfile
DDPTool 1.0.0 does not build with Alpine 3.13.
Temporary fix is setting alpine container to a specific
version where DDPTool builds ok.
Fix to DDPTool itself will follow next week.
> Set alpine to specific version to fix DDPTool build

- .travis.yml
- pkg/utils/testing.go
This temporarily fixes a unit test error in travis
where pci.ids doesn't exist in the fake filesystem
and ghw lib tries to download it from internet, but
fails to unzip the downloaded package header.
Signed-off-by: Zenghui Shi <zshi@redhat.com>
> Add pci.ids file in test filesystem

- pkg/accelerator/accelDeviceProvider.go
- pkg/accelerator/accelDeviceProvider_test.go
Filtering based on PCI addresses is missing
> PCI address based filtering for accelerator device type is not supported

- images/Dockerfile
Alpine 3.13 set APK repositories to https instead of http.
APK does not work with https proxy because of libfetch issue.
Set alpine to 3.12 until issue is resolved.
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
See: 
https://github.com/alpinelinux/docker-alpine/issues/136
https://github.com/alpinelinux/docker-alpine/issues/98
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220468
Partially fixes #315
> Fix alpine 3.13 APK proxy build issue

- images/Dockerfile
Fixed errors:
DL3020 Use COPY instead of ADD for files and folders
DL3003 Use WORKDIR to switch to a directory
DL3019 Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages
Remaining errors:
DL3018 Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
(It's probably safer to not pin versions in case they aren't available in the future, which might cause the build to fail.)
DL3006 Always tag the version of an image explicitly (community discussion is required to establish which version of alpine should be used). 
Fixes #315
> fix hadolint errors

- Makefile
Keep all variables at the top of the file
Remove unused and/or unnecessary variables
Delete unnecessary comments
Fixes https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/291
> Clean up Makefile variables and comments

- CONTRIBUTING.md
Re-adding NPWG slack auto invite mechanism. Non-Intel users
need mechanism to join NPWG slack.
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
I misunderstood slacks invite mechanism for non-Intel users. Non-Intel users require invite. Re-adding invite mechanism. 
I attempted to change URL of invite mechanism but failed. Slack only grands auto invite rights to enterprise workspaces. See here outsideris/slack-invite-automation#146
Currently, the intel-corp.heroku.com app relies on slacks legacy token mechanism to accomplish this. This will fail in the future when legacy tokens are deprecated. I think this should be discussed at NPWG level but in the mean time, I propose re-adding auto invite mechanism.
> Fix auto invite to NPWG slack

- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
Containers without memory limits are more likely to be
terminated when the node runs out of memory. Ring fencing
memory ensures our service is isolated.
Containers without cpu limits can exceed the capacity of the
node and affect performance of the host and other containers.
CPU/memory information was gathered from "docker stats ..".
~20mb is normal operating memory footprint.
There is also DOS considerations if our service is compromised.
> set memory/cpu requests/limits

- README.md
Link to host-device CNI plugin page in the README is currently https://www.cni.dev/plugins/main/host-device/ which is broken.
> Fix broken URL link to host-device CNI plugin page

- go.mod
- go.sum
For Go 1.16, No automatic changes to go.mod and go.sum [1].
Previously, if Go found a problem in go.mod or go.sum,
it would attempt to fix however this feature is not
available for 1.16.
[1] https://blog.golang.org/go116-module-changes
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
#330
> Update go mod / sum to fix Go 1.16 build

- docs/ddp/README.md
- docs/ddp/e800/configMap.yaml
- docs/ddp/e800/crd-sriov-comms.yaml
- docs/ddp/e800/crd-sriov-default.yaml
- docs/ddp/e800/pod-comms.yaml
- docs/ddp/e800/pod-default.yaml
- docs/ddp/x700/configMap.yaml
- docs/ddp/x700/crd-sriov-gtp.yaml
- docs/ddp/x700/crd-sriov-pppoe.yaml
- docs/ddp/x700/pod-gtp.yaml
- docs/ddp/x700/pod-pppoe.yaml
Update DDP README to add E800 series
Add E800 series examples
> Update DDP docs to include E800 series

- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
Based on the github actions in the sriov-operator project, add the same kind of actions here.
We did not have a non-rhel Dockerfile in this project, so I added one
Signed-off-by: Manuel Buil <mbuil@suse.com>
> Add github actions

- go.mod
- go.sum
While working with Device Plugin SNYK scan reported vulnerability in containernetworking/cni module, therefore decided to update the module.
Vulnerability's details below:
**HIGH SEVERITY
Directory Traversal** 
Vulnerable module:	github.com/containernetworking/cni/pkg/invoke
Introduced through:	github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils@#9d213757d22d
Exploit maturity:	No known exploit
Fixed in:	0.8.1
**Detailed paths**
Introduced through: github.com/k8snetworkplumbingwg/sriov-network-device-plugin@0.0.0 › github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils@#9d213757d22d › github.com/containernetworking/cni/libcni@0.8.0 › github.com/containernetworking/cni/pkg/invoke@0.8.0
**Overview**
Affected versions of this package are …
> Upgrade containernetworking/cni dependency

- deployments/configMap.yaml
> Fix sample configmap to include IAVF device ID

- cmd/sriovdp/manager.go
With this patch the config is logged before the error is returned.
When the user looks through the logs they will be able to see their config,
along with a message asking them to check if config is in json format.
Signed-off-by: John O'Loughlin <john.oloughlin@intel.com>
> Make it easier for the end user to debug issues with their sriov config

- README.md
This PR corrects a typo I've found while reading the README.md file
> Fixed a typo  in README.md(resrouce->resource)

- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
- Makefile
- README.md
- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
- docs/config-file/README.md
- images/README.md
@zshi-redhat I can make further updates to this by creating a new tagged release, so we can update the rest of the deployment artifacts. Currently, we only have a version package for 'latest'.
> Change to GHCR image path

- docs/ddp/README.md
version 1.0.0.0 of DDP tool doesn't support E810 Series NICs
Updating Docs to make note of this.
@zshi-redhat
> Updating DDP Docs

- cmd/sriovdp/manager.go
filteredDevices may be empty when excluding allocated devices
which results in failure initializing servers:
```
I1103 07:44:28.118760 1680023 manager.go:110] Creating new ResourcePool: dpdk
I1103 07:44:28.118764 1680023 manager.go:111] DeviceType: netDevice
W1103 07:44:28.121483 1680023 manager.go:152] Cannot add PCI Address [0000:3b:0a.0]. Already allocated.
W1103 07:44:28.121494 1680023 manager.go:152] Cannot add PCI Address [0000:3b:0a.1]. Already allocated.
E1103 07:44:28.121500 1680023 manager.go:136] initServers(): error creating ResourceServer: factory: unable to get resource pool object
E1103 07:44:28.121530 1680023 main.go:68] error initializing resource servers factory: unable to get resource pool object
```
Signed-off-by: Zenghui Shi <zshi@redhat.com>
> Fix empty filteredDevices

- README.md
- pkg/netdevice/netInfoProviders.go
- pkg/netdevice/pciNetDevice_test.go
- pkg/netdevice/vhostNet.go
This commit add also the tun device into the container.
This is needed to create tap devices inside the container network namespace
Vhost-net is used to accelerate the dpdk connected to kernel networking using tap devices.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
> Add the tun mounting with vhost is requested

- CONTRIBUTING.md
- README.md
SRIOV network device plugin supports discovery and allocation of non SR-IOV network devices.
Align documentation with this use-case.
In addition, fix typo in CONTRIBUTING doc (separate commit in this PR)
> Update doc with pci pf support

- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
Proposal for the future:
Using a specific version of the plugin in deployment examples requires updating it for each release. This poses a risk of users
deploying an older version of the plugin than the specific one they checked out.
The proposal is to always use `latest` and then in every release, update yaml for the release and upload it to the release page.
> Bump plugin version to v3.4.0 in deployment examples

- images/Dockerfile
alpine image has been pinned to 3.12 due to issues
that have already been resolved.
since sriov-network-device plugin image now properly builds
with latest alpine images, we can set it in Dockerfile.
As an additional benefit this will fix container image
related security vulnerabilities as new images are published.
> Update alpine image in Dockerfile

- pkg/accelerator/accelDevice.go
- pkg/accelerator/accelDeviceProvider.go
- pkg/accelerator/accelDevice_test.go
- pkg/netdevice/pciNetDevice.go
- pkg/netdevice/pciNetDevice_test.go
- pkg/resources/pciDevice.go
- pkg/types/types.go
This change adds support for making advertising of NUMA node optional.
This can be done per resource pool by setting the config
"exclude_topology" to true. Default behavior is to advertise NUMA node
information.
#320 
Signed-off-by: Ravindra Thakur <ravindra.nath.thakur@est.tech>
> Make advertising of NUMA node optional

- README.md
Updated README to include documentation for "excludeTopology" config.
This config allows making advertising of device's NUMA toplogy optional.
#320 
Signed-off-by: Ravindra Thakur <ravindra.nath.thakur@est.tech>
> Update docs for excludeTopology config

- .github/workflows/build-test-lint.yml
- .gitignore
- .golangci.yml
- Makefile
- README.md
> Make code coverage profile output deterministic, in
> order to be collected by coveralls.io step.
> 
> Add coveralls badge to README.md
> 
> Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
Coverage on this repository is [~77%](https://coveralls.io/github/zeeke/sriov-network-device-plugin). That's a very good percentage and this PR makes it recorded in future PRs.
If it is appreciated, I can add a coverage threshold to GH actions as described in [this blog post](https://medium.com/synechron/how-to-set-up-a-test-coverage-threshold-in-go-and-github-167f69b940dc).
> Add Coveralls step in GH actions

- Makefile
Downloading binaries with go get may change the
content of go.mod file and it is deprecated in go1.17.
`go install` should be used instead.
Fixes #427
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
> Use `go install` to download binaries

- pkg/accelerator/accelResourcePool.go
- pkg/accelerator/accelResourcePool_test.go
- pkg/factory/factory.go
- pkg/netdevice/netResourcePool.go
- pkg/netdevice/netResourcePool_test.go
- pkg/resources/pool_stub.go
- pkg/resources/pool_stub_test.go
This commit removes `devices` map from ResourcePoolImpl
and uses devicePool map instead in GetDevices() method.
This is done to avoid duplication by holding API devices
in two places.
In addition, add unit-test for GetDevices().
> Remove API devices from reosurcePool

- pkg/resources/pciDevice.go
- pkg/types/mocks/AccelDevice.go
- pkg/types/mocks/PciDevice.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
This check is done by utility function with the same name, hence
remove method as unused.
Signed-off-by: Dmytro Linkin <dlinkin@nvidia.com>
> Remove IsSriovPF as unused method of PciDevice interface

- pkg/netdevice/netInfoProviders.go
- pkg/netdevice/netResourcePool.go
- pkg/netdevice/vdpa.go
- pkg/resources/vfioInfoProvider.go
- pkg/utils/ddp_test.go
I've noticed that golangci-lint throws some errors (go fmt formatting) on current codebase. Fixed those quickly.
> Fixed linter issues

- deployments/sriovdp-daemonset.yaml
- move yaml to deployment root dir as we dont maintain yamls for multiple k8s versions
- align amd64 daemonset to deploy latest like other arch
- use kubernetes.io/arch label instead of beta.kubernetes.io/arch as it is deprecated
Signed-off-by: adrianc <adrianc@nvidia.com>
> Update sriov device plugin deployment

- images/Dockerfile
due to recent update of gcc in builder base image
compilation of ddptool fails.
split ddptool build to its own container and fix alpine version.
this will allow to control the base image which is used to build device plugin and ddptool separately.
once ddptool is updated, its alpine base image version can be bumped
Signed-off-by: adrianc <adrianc@nvidia.com>
> Move ddptool build to its own continer

- docs/config-file/README.md
The label `beta.kubernetes.io/arch` has been deprecated for a long time
> Remove deprecated label: beta.kubernetes.io/arch

- pkg/utils/testing.go
Remove ioutil for go version:https://go.dev/doc/go1.16#ioutil
> Cleanup: remove ioutil for go version

- pkg/types/types.go
As recently the implementation changed
to expose additional device informaiton,
we should align comment to describe new
behaviour.
> Update GetEnvVal docstring

- pkg/auxnetdevice/auxNetDeviceProvider.go
It is legal to use auxiliary devices of system default interface.
> auxnetdevice: Don't skip PCI network devices with default route

- cmd/sriovdp/manager_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
according to
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.proto#L41, resource name is expected to be a DNS lable so dash should be allowed
Fixes: #476
> allow dash "-" in resource name

- .github/workflows/build-test-lint.yml
- go.mod
- go.sum
- images/Dockerfile
bumping go version to 1.20.
#475 needs a go version greater than 1.17, SRIOV CNI is go 1.20, so updating to stay in line.
all these passed:
```
make build
make image
go test ./...
```
> bump go version to 1.20

- .github/workflows/build-test-lint.yml
This pull request enables race detection in unit tests by modifying the test step in build-test-lint.yml to include the '-race' flag by running  make test-race, enabling race detection in the CI during testing.
Race detection can help identifying potential data race conditions, which can lead to hard-to-debug issues in concurrent code. By enabling race detection in our unit tests, we can detect and address these race conditions, ensuring the reliability and stability of our code. (for further reference view: https://go.dev/doc/articles/race_detector)
> Enable race detection in unit tests

- deployments/sriovdp-daemonset.yaml
Modern kubernetes does not set the `master` designation any longer.  This patch adds in support for `control-plane` while preserving the old behavior.
> Recognize modern taint in demo

- deployments/sriovdp-daemonset.yaml
- images/README.md
There is no need to mount the whole '/var/lib/kubelet/' directory into a pod. It's enough to mount only '/var/lib/kubelet/device-plugins' and '/var/lib/kubelet/plugins_registry' directories.
> Update device plugins volumes mounts

- .github/workflows/image-push-release.yml
> Fix push-manifest github action job for release

- README.md
- deployments/configMap.yaml
We have verified that SRIOV plugin works with Broadcom NICs. This request is adding Broadcom NICs to Readme and adding an example of a working configuration.
> Add support for Broadcom NICs

- .github/workflows/image-push-release.yml
- disable latest tag generation in docker meta action
- remove un-needed IMAGE_NAME var from manifest creation, docker meta tags is already with the full name.
> Fix image push worklow for release

- pkg/devices/gen_net.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
In case we fail to get Uplink Representor, fallback to get PF PCI address and use sysfs to get PF netdevice.
This is needed in case a device supports the creation of Auxiliary devices but is not in switchdev.
> Add fallback to get PF Name for AuxNetDevice

- .github/workflows/build-test-lint.yml
- .golangci.yml
- go.mod
- go.sum
- images/Dockerfile
- pkg/resources/server.go
- pkg/resources/testing.go
- pkg/utils/utils.go
Upcoming changes will require go 1.21 so it's better to update the toolchain separately
> Update go version and github actions to 1.21

- README.md
- go.mod
- go.sum
- pkg/factory/factory.go
- pkg/factory/factory_test.go
- pkg/netdevice/netDeviceProvider.go
- pkg/netdevice/pciNetDevice.go
- pkg/resources/pKeySelector.go
- pkg/resources/pKeySelector_test.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
- pkg/utils/mocks/SriovnetProvider.go
- pkg/utils/sriovnet_provider.go
- pkg/utils/utils.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/.gitignore
- vendor/github.com/k8snetworkplumbingwg/sriovnet/.golangci.yml
- vendor/github.com/k8snetworkplumbingwg/sriovnet/Makefile
- vendor/github.com/k8snetworkplumbingwg/sriovnet/errors.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/file_access.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/mofed_ib_helper.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/sriovnet.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/sriovnet_aux.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/sriovnet_helper.go
- vendor/github.com/k8snetworkplumbingwg/sriovnet/sriovnet_switchdev.go
- vendor/github.com/spf13/afero/memmap.go
- vendor/github.com/spf13/afero/unionFile.go
- vendor/modules.txt
This PR introduced a new kind of device selector based on [Infiniband Partition Key](https://docs.nvidia.com/networking/display/winof2v310lts/infiniband+network#src-106007664_InfiniBandNetwork-PKeys).
The PKey retrieval functionality is taken from sriovnet. This PR will be finalized with updated sriovnet dependency when the ([related PR there](https://github.com/k8snetworkplumbingwg/sriovnet/pull/69)) is merged
> Allow to filter net devices by Infiniband Partition Key

- images/Dockerfile
Upgrading to golang:1.21-alpine3.19 caused the ddp build to fail: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/actions/runs/7738698140
Let's downgrade it until the root cause is found
> Downgrade ddp-builder container version

- pkg/netdevice/netResourcePool.go
- pkg/netdevice/netResourcePool_test.go
The DeviceInfoSpec allows to specify rdma device for a pci device: https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/blob/master/pkg/apis/k8s.cni.cncf.io/v1/types.go#L63
Multus propagates device spec to the network-status, so it's easy to track which RDMA device is allocated to a POD:
```
k8s.v1.cni.cncf.io/network-status:
[{
"name": "k8s-pod-network",
"ips": [
"192.168.107.206"
],
"default": true,
"dns": {}
},{
"name": "default/sriov-net1",
"interface": "net1",
"ips": [
"10.56.217.2"
],
"mac": "7a:bb:87:d9:b4:94",
"dns": {},
"device-info": {
"type": "pci",
"version": "1.1.0",
"pci": {
"pci-address": "0000:03:00.3",
"rdma-device": "mlx5_4"
}
},
"gateway": [
"\u003cnil\u003e"
]
}]
```
This change can serve two purposes:
1. Simplify debugging. Users can just query …
> Expose RDMA device name in the devicespec if available

- .github/workflows/build-test-lint.yml
- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
Reverts k8snetworkplumbingwg/sriov-network-device-plugin#540
as it breaks the image push actions
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/actions/runs/9091929799
```
[Invalid workflow file: .github/workflows/image-push-master.yml#L10](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/actions/runs/9091929799/workflow)
The workflow is not valid. .github/workflows/image-push-master.yml (Line: 10, Col: 9): Unrecognized named-value: 'env'. Located at position 28 within expression: github.repository_owner == env.image-push-owner .github/workflows/image-push-master.yml (Line: 41, Col: 9): Unrecognized named-value: 'env'. Located at position 28 within expression: github.repository_owner == env.image-push-owner
```
Looks like `jobs.<job_id>.if ` does …
> Revert "🌱 Making workflows not run on forks."

- .github/workflows/build-test-lint.yml
- go.mod
- images/Dockerfile
Updating the build to go v1.22 is a requirement
for bumping to `k8s.io/kubelet@v1.30`
needed for:
- https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/562
> Build with go `v1.22`

- .github/workflows/build-test-lint.yml
- .golangci.yml
- Makefile
- cleanup makefile
- update workflows
- remove deprecated linters from .golangci.yml
- allow to provide additional GO build options, ldflags and flags
> cleanup makefile

- .github/workflows/build-test-lint.yml
This fixes
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`
```
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/actions/runs/13287834864/job/37388698220?pr=628
> Bump `actions/upload-artifact@v4`

- pkg/auxnetdevice/auxNetDevice.go
- pkg/auxnetdevice/auxNetDevice_test.go
support for additionInfo config object for Auxiliary network devices to provide addtional information to sf's created for Mellanox BlueField-2
Fixes #627
> additionInfo config object for Auxiliary network devices

- pkg/resources/server.go
This PR addresses an issue where the SR-IOV device plugin's gRPC server would terminate unexpectedly due to a transient error during the ListAndWatch operation. This premature shutdown led to false reporting of zero available Mellanox SR-IOV VFIO resources, causing affected nodes to be marked as unschedulable.
The gRPC server no longer stops the server when a transient error occurs when it attempts to advertise resources.
Instead, the error is logged, and an err is returned allowing the server to continue running and giving the device plugin an opportunity to recover through the kubelet's  retry.
Additionally, the Watch method already includes this code https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/5cc9452448734b5ca01c7441f3de9a2ba48f4724/pkg/resources/server.go# …
> Fixes #648 Return an err on transient failures rather than stopping the server to allow for retry
