- glide.yaml
Change-Id: I5b3b70cb722be2560f77be5ea19c857eca803acd
> updated glide.yaml with correct package name

- checkpoint/checkpoint.go
- cmd/sriovdp/sriov-device-plugin.go
Change-Id: I52072035a80f2cff6b781d530f8a8381b7c81d66
> added state restoring from checkpoint file

- deployments/Dockerfile
- deployments/build_docker.sh
- images/Dockerfile
- images/README.md
- images/build_docker.sh
- images/entrypoint.sh
- images/sriovdp-daemonset.yaml
Adds a Docker image for distribution of sriovdp
binary in a Docker image.
> [docker-image] Adds a Docker image for distribution

- cmd/sriovdp/sriov-device-plugin.go
- images/entrypoint.sh
- images/sriovdp-daemonset.yaml
This commit also makes sure glog.Flush() is called;
otherwise logging message may not be saved in file.
> [docker-image] Enable settings of logging directory and level

- glide.yaml
This code fixes error at 'glide up'. I've verified no error message at 'glide up' command.
> Fix glide.yaml for the error at 'glide up'

- cmd/sriovdp/sriov-device-plugin.go
Detects Link status for Linux network devices and
updates associated VFs health state accordingly every
5 seconds.
Add GetVFList util and simplify discoverNetworks.
Add rootDevices in sriovManager to track discovered
and SR-IOV enabled PF devices.
> add link status detection

- Dockerfile
- images/sriovdp-daemonset.yaml
Don't log to /var/log/ by default
Fix golang package install in Dockerfile
> fixes default log dir and golang pkg install

- pkg/utils/utils.go
this change will fix issue describe in #40
Change-Id: I8272bc711b73a35f6ea619bf1016bea2f408ea95
> fix PF only link health check

- deployments/flannel-network.yaml
Update flannel-network.yaml with k8s.cni.cncf.io/v1
and NetworkAttachmentDefinition
Change-Id: I7916688e75b6679a2f3fa500bf3918179646c5ad
> Fix flannel-network.yaml

- deployments/pod-tc1.yaml
- deployments/pod-tc2.yaml
- deployments/pod-tc3.yaml
The doc is not containing steps to attach label to the node
so to make this pod to work we need to remove the labels
from the pod-tc yaml files
Change-Id: I11d6f24f6e8354a694cb55cbfdd17087de9f4348
Signed-off-by: Moshe Levi <moshele@mellanox.com>
> Remove labels from pod-tc yaml

- deployments/pod-sriovdp.yaml
Due to change to alpine image and since "bash" command not
existing it shoud be changed to "sh" command
Fixes #71
> Fix starting device plugin issue

- Dockerfile.rhel
Signed-off-by: mamduhala <mamduhala@mellanox.com>
> Fix typo in Dockerfile.rhel

- README.md
- deployments/pod-sriovdp.yaml
Signed-off-by: mamduhala <mamduhala@mellanox.com>
> Modify pod-sriovdp.yaml to run device plugin when create the pod

- deployments/pod-sriovdp.yaml
> Use device plugin image with release-v1 tag

- README.md
> fix readme reference

- Makefile
> remove vendor dependencies for build/lint/test rules in Makefile

- Makefile
Reverts intel/sriov-network-device-plugin#113
> Revert "remove vendor dependencies for build/lint/test rules in Makefile"

- README.md
- deployments/config.json
- images/configMap.yaml
- pkg/resources/deviceSelectors.go
- pkg/resources/deviceSelectors_test.go
- pkg/resources/factory.go
- pkg/resources/factory_test.go
- pkg/resources/pciNetDevice.go
- pkg/resources/pciNetDevice_test.go
- pkg/resources/pool_stub_test.go
- pkg/resources/server_test.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
- pkg/utils/utils.go
Filtering the resources by the PF device name
Signed-off-by: mamduhala <mamduhala@mellanox.com>
> Add filtering By PF Names

- cmd/sriovdp/manager.go
Signed-off-by: Moshe Levi <moshele@mellanox.com>
> fix typo in plugin detect watchmode

- README.md
Adding go report card https://goreportcard.com/report/github.com/intel/sriov-network-device-plugin
> README.md: add go report card

- docs/README.md
- docs/dpdk/README.md
- docs/dpdk/configMap.yaml
- docs/dpdk/crd-dpdk-net2000.yaml
- docs/dpdk/pod_testpmd.yaml
- docs/dpdk/sriovdp-daemonset.yaml
Change-Id: I918a997db461d71a32c4c65d7a389d9bbc096358
> docs: add sample dpdk app deployment

- README.md
The document was generalized to mention that the DP works together with any meta plugin supporting the DP based network provisioning.
Deployment example continue to mention Multus in the first place, but also added DANM to showcase the flexibility of the plugin.
Also touched up the document at a couple of places: broken links deleted, out of date information updated, some English corrected.
I rearranged the order of proposed installation because IMO it is more logical to start with the CNI and the DP first, but can change it back if you prefer the original way :)
> Add DANM as a compatible meta plugin option to the README, in addition to Multus

- README.md
- pkg/resources/deviceSelectors.go
- pkg/resources/pciNetDevice.go
- pkg/types/mocks/PciNetDevice.go
- pkg/types/types.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
As was discussed in issue [#157](https://github.com/intel/sriov-network-device-plugin/issues/157).
> Implement selector based on PF name + VF index

- README.md
Fixed typo causing trouble in issue #204
> fixed pfName typo in README

- docs/bond/README.md
- docs/bond/bond-crd.yaml
- docs/bond/sriov-net.yaml
- docs/bond/test-pod.yaml
Added documentation on how to set up bond cni with sriov - as per [comment  ](https://github.com/intel/bond-cni/pull/4#issuecomment-582868917)
> Docs and files for bond cni usage

- .travis.yml
- Makefile
- README.md
- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
- images/Dockerfile.ppc64le
Add CI job for ppc64le machine and create a manifest for the image
in both amd64 and ppc64le archs
Signed-off-by: mamduhala <mamduhala@mellanox.com>
> Support multi arch travis-ci job and docker image

- pkg/types/types.go
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
> Add small comment for the device type list

- Dockerfile.rhel7
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
> Update rhel7 builder image go version

- deployments/k8s-v1.10-v1.15/sriovdp-daemonset.yaml
- deployments/k8s-v1.16/sriovdp-daemonset.yaml
With image imagePullPolicy set to IfNotPreset the user doesn't need to pull the image manually
> Change daemonset imagePullPolicy from Never to IfNotPreset

- deployments/k8s-v1.16/sriovdp-daemonset.yaml
- images/Dockerfile.arm64
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>
> Add arm64 build instructions and daemon set

- docs/vf-setup.md
Update vf-setup with instructions to alternatively
configure NIC firmware with mstconfig tool.
Signed-off-by: Adrian Chiris <adrianc@mellanox.com>
> Update SR-IOV configurations for Mellanox NICs

- deployments/configMap.yaml
Added more recent driver version as it's now default with most distributions.
> added iavf driver to configmap

- CONTRIBUTING.md
This commit adds a meeting, patch format sections
and performs some minor refactoring to the document
> Update Contributing doc

- README.md
Signed-off-by: Zenghui Shi <zshi@redhat.com>
> Add CNI content for virtualized deployments in Readme

- Makefile
Add missing help description
Fixes https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/292
> Fix make help description and logging info

- README.md
Intel inititive to modernize terminology.
> Replace outdated terminology in README

- Makefile
Makefile should be able to delete everything it creates
Fixes https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/293
> Delete all cached data, /bin, /build and /test directories

- CONTRIBUTING.md
Signed-off-by: Kennelly, Martin <martin.kennelly@intel.com>
> Add additional meeting info & update Slack URL

- README.md
> Add extra supported HW and fix links in readme

- cmd/sriovdp/manager.go
- go.mod
- pkg/factory/factory_test.go
- pkg/netdevice/netDeviceProvider.go
- pkg/resources/pciDevice.go
- pkg/resources/server.go
- pkg/resources/testing.go
- pkg/utils/testing.go
- pkg/utils/utils.go
This commit handles remaining lint issues.
> Fix Remaining lint issues

- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
supports multi-arch image manifest
> supports multi-arch image manifest

- .github/workflows/build-test-lint.yml
- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
workflows complain about deprecated actions.
align actions to their latest version.
it may be relates to #470 , if it doesnt solve it, its a good start :)
> Bump github actions to their latests versions

- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
use docker buildx image tools to create
manifest out of manifest which is how
images are currently being built and pushed
> fix CI manifest push flow

- .github/workflows/build-test-lint.yml
- .github/workflows/codeql.yml
- .github/workflows/image-push-master.yml
- .github/workflows/image-push-release.yml
> chore: align runners

- .github/dependabot.yaml
- .github/workflows/build-test-lint.yml
this will trigger gh actions version bumps using dependabot
> chore: add github-actions to dependabot

- .github/dependabot.yaml
> fix: dependabot config
